# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
spec: src/**/*.spec.ts
bail: true
extension:
- ts
reporter: spec
require: ts-node/register
timeout: 3000 # For log upgrades.
watch: false # Default is false, but leaving this here to make it easy to switch on.
