name: Create Release
on:
  workflow_dispatch:

jobs:
  createPrerelease:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      # Release creation
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
        name: npm install
      - run: npm install --global @vscode/vsce
        name: Install vsce
      - run: vsce package
        name: Create VSIX
      - id: package_version
        uses: Saionaro/extract-package-version@a5ea15b23669502732d230f62cabfa92fb137a38 # v1.4.0
      - id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package_version.outputs.version }}
          release_name: ${{ steps.package_version.outputs.version }}
      - uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sarif-viewer-${{ steps.package_version.outputs.version }}.vsix
          asset_name: sarif-viewer-${{ steps.package_version.outputs.version }}.vsix
          asset_content_type: application/vsix
